
insert into HOUSE_ENTITY (id,name,unit_price,area, description,landlord_entity_id)
values (1,"Penthouse",1000,100,"You will fell like a king.", "Kris")
insert into HOUSE_ENTITY (id,name,unit_price,area, description,landlord_entity_id)
values (2,"Flat",100,25,"You will fell like a student.","John")
insert into HOUSE_ENTITY (id,name,unit_price,area, description,landlord_entity_id)
values (3,"SemiDetachedHouse",500,110,"You will fell like a family member.","Mat")

insert into LANDLORD_ENTITY (id,name)
values (1, "Kris")
insert into LANDLORD_ENTITY (id,name)
values (2, "John")
insert into LANDLORD_ENTITY (id,name)
values (3, "Mat")

insert into TENANT_ENTITY (id,name)
values (1, "Anna")
insert into TENANT_ENTITY (id,name)
values (2, "Jane")
insert into TENANT_ENTITY (id,name)
values (3, "Rebeca")
